/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lucie
 */
import javax.swing.*;

public class FenetreAccueil extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreAccueil.class.getName());

    /**
     * Creates new form FenetreAccueil
     */
    public FenetreAccueil() {
        initComponents();
        this.setTitle("La Chevauchée Fantastique");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_accueil = new javax.swing.JLabel();
        btn_jouer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_accueil.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        txt_accueil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_accueil.setText("Bienvenu sur la chevauchée fantastique");
        getContentPane().add(txt_accueil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 400, -1));

        btn_jouer.setText("Jouer");
        btn_jouer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_jouerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_jouer, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_jouerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_jouerActionPerformed
    Interface jeuFenetre = new Interface();
    jeuFenetre.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btn_jouerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetreAccueil().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_jouer;
    private javax.swing.JLabel txt_accueil;
    // End of variables declaration//GEN-END:variables
}
