/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lucie
 */
public class Interface extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interface.class.getName());

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_11 = new javax.swing.JButton();
        btn_12 = new javax.swing.JButton();
        btn_13 = new javax.swing.JButton();
        btn_14 = new javax.swing.JButton();
        btn_15 = new javax.swing.JButton();
        btn_21 = new javax.swing.JButton();
        btn_22 = new javax.swing.JButton();
        btn_23 = new javax.swing.JButton();
        btn_24 = new javax.swing.JButton();
        btn_25 = new javax.swing.JButton();
        btn_31 = new javax.swing.JButton();
        btn_32 = new javax.swing.JButton();
        btn_33 = new javax.swing.JButton();
        btn_34 = new javax.swing.JButton();
        btn_35 = new javax.swing.JButton();
        btn_41 = new javax.swing.JButton();
        btn_42 = new javax.swing.JButton();
        btn_43 = new javax.swing.JButton();
        btn_44 = new javax.swing.JButton();
        btn_45 = new javax.swing.JButton();
        btn_51 = new javax.swing.JButton();
        btn_52 = new javax.swing.JButton();
        btn_53 = new javax.swing.JButton();
        btn_54 = new javax.swing.JButton();
        btn_55 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.GridLayout(5, 5));

        btn_11.setText("case11");
        btn_11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_11ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_11);

        btn_12.setText("case12");
        btn_12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_12ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_12);

        btn_13.setText("case13");
        btn_13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_13ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_13);

        btn_14.setText("case14");
        btn_14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_14ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_14);

        btn_15.setText("case15");
        btn_15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_15ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_15);

        btn_21.setText("case21");
        btn_21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_21ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_21);

        btn_22.setText("case22");
        btn_22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_22ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_22);

        btn_23.setText("case23");
        btn_23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_23ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_23);

        btn_24.setText("case24");
        btn_24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_24ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_24);

        btn_25.setText("case25");
        btn_25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_25ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_25);

        btn_31.setText("case31");
        btn_31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_31ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_31);

        btn_32.setText("case32");
        btn_32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_32ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_32);

        btn_33.setText("case33");
        btn_33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_33ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_33);

        btn_34.setText("case34");
        btn_34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_34ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_34);

        btn_35.setText("case35");
        btn_35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_35ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_35);

        btn_41.setText("case41");
        btn_41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_41ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_41);

        btn_42.setText("case42");
        btn_42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_42ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_42);

        btn_43.setText("case43");
        btn_43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_43ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_43);

        btn_44.setText("case44");
        btn_44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_44ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_44);

        btn_45.setText("case45");
        btn_45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_45ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_45);

        btn_51.setText("case51");
        btn_51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_51ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_51);

        btn_52.setText("case52");
        btn_52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_52ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_52);

        btn_53.setText("case53");
        btn_53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_53ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_53);

        btn_54.setText("case54");
        btn_54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_54ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_54);

        btn_55.setText("case55");
        btn_55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_55ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_55);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 5, 390, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_11ActionPerformed

    private void btn_23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_23ActionPerformed

    private void btn_12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_12ActionPerformed

    private void btn_13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_13ActionPerformed

    private void btn_14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_14ActionPerformed

    private void btn_15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_15ActionPerformed

    private void btn_21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_21ActionPerformed

    private void btn_22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_22ActionPerformed

    private void btn_24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_24ActionPerformed

    private void btn_25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_25ActionPerformed

    private void btn_31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_31ActionPerformed

    private void btn_32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_32ActionPerformed

    private void btn_33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_33ActionPerformed

    private void btn_34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_34ActionPerformed

    private void btn_35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_35ActionPerformed

    private void btn_41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_41ActionPerformed

    private void btn_42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_42ActionPerformed

    private void btn_43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_43ActionPerformed

    private void btn_44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_44ActionPerformed

    private void btn_45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_45ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_45ActionPerformed

    private void btn_51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_51ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_51ActionPerformed

    private void btn_52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_52ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_52ActionPerformed

    private void btn_53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_53ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_53ActionPerformed

    private void btn_54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_54ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_54ActionPerformed

    private void btn_55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_55ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_55ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interface().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_11;
    private javax.swing.JButton btn_12;
    private javax.swing.JButton btn_13;
    private javax.swing.JButton btn_14;
    private javax.swing.JButton btn_15;
    private javax.swing.JButton btn_21;
    private javax.swing.JButton btn_22;
    private javax.swing.JButton btn_23;
    private javax.swing.JButton btn_24;
    private javax.swing.JButton btn_25;
    private javax.swing.JButton btn_31;
    private javax.swing.JButton btn_32;
    private javax.swing.JButton btn_33;
    private javax.swing.JButton btn_34;
    private javax.swing.JButton btn_35;
    private javax.swing.JButton btn_41;
    private javax.swing.JButton btn_42;
    private javax.swing.JButton btn_43;
    private javax.swing.JButton btn_44;
    private javax.swing.JButton btn_45;
    private javax.swing.JButton btn_51;
    private javax.swing.JButton btn_52;
    private javax.swing.JButton btn_53;
    private javax.swing.JButton btn_54;
    private javax.swing.JButton btn_55;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
