/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lucie
 */

import javax.swing.*;
import java.awt.*;

public class Interface extends javax.swing.JFrame {
    private JeuChevaucheeFantastique jeu;
    private CelluleGraphique[][] grille;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interface.class.getName());

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        jeu = new JeuChevaucheeFantastique();
        
        int t = jeu.getTaille();
        grille = new CelluleGraphique[t][t];
        
        this.getContentPane().setLayout(new GridLayout(t, t));

        for (int i = 0; i < t; i++) {
        for (int j = 0; j < t; j++) {
            final int r = i;
            final int c = j;
            grille[i][j] = new CelluleGraphique();
            
            grille[i][j].addActionListener(e -> {
                
                if (jeu.deplacerCavalier(r, c)) {
                    rafraichir();
                    
                    if (jeu.estTermine()) {
                        JOptionPane.showMessageDialog(this, "Niveau Gagné !");
                        jeu.initialiserNiveau(jeu.getNiveauActuel() + 1);
                        rafraichir();
                    } 
                    else if (!jeu.peutEncoreJouer()) {
                        JOptionPane.showMessageDialog(this, "Bloqué ! Plus de mouvements possibles. Recommençons.");
                        jeu.initialiserNiveau(jeu.getNiveauActuel()); 
                        rafraichir();
                    }
                }
            });
            this.getContentPane().add(grille[i][j]);
        }
    }
    
    rafraichir();
    this.setSize(600, 600);
}
    
    private void rafraichir() {
        Case cp = jeu.getPosCavalier();
        for (int i = 0; i < jeu.getTaille(); i++) {
            for (int j = 0; j < jeu.getTaille(); j++) {
                boolean estCav = (cp.getLigne() == i && cp.getColonne() == j);
                grille[i][j].maj(jeu.getEtatCase(i, j), estCav, (i + j) % 2 == 0);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(() -> new Interface().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
