/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lucie
 */
public class interfaceGraphique extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(interfaceGraphique.class.getName());
    private int nbClics;

    /**
     * Creates new form interfaceGraphique
     */
    public interfaceGraphique() {
        initComponents();
        
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_msg_bienvenue = new javax.swing.JLabel();
        bouton_principal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_msg_bienvenue.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        label_msg_bienvenue.setForeground(new java.awt.Color(255, 0, 0));
        label_msg_bienvenue.setText("bonjour");
        getContentPane().add(label_msg_bienvenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 66, -1, -1));

        bouton_principal.setText("OK");
        bouton_principal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_principalActionPerformed(evt);
            }
        });
        getContentPane().add(bouton_principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 195, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bouton_principalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_principalActionPerformed
        if (nbClics == 0) label_msg_bienvenue.setText("hello");
        if (nbClics == 1) label_msg_bienvenue.setText("HELLO");
        if (nbClics == 2) label_msg_bienvenue.setText("YOOOO");
        if (nbClics == 2) {
            
        }
        
    }//GEN-LAST:event_bouton_principalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new interfaceGraphique().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_principal;
    private javax.swing.JLabel label_msg_bienvenue;
    // End of variables declaration//GEN-END:variables
}
