/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lucie
 */

public class FenetreAccueil extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreAccueil.class.getName());

    /**
     * Creates new form FenetreAccueil
     */
    public FenetreAccueil() {
        initComponents();
    }

    private void lancerJeu(CadenasJeu.NiveauDifficulte niveau) {
        Interface jeuInterface = new Interface(niveau);
        jeuInterface.setVisible(true);
        this.dispose(); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_facile = new javax.swing.JButton();
        btn_normal = new javax.swing.JButton();
        btn_difficile = new javax.swing.JButton();
        lbl_niveau = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_facile.setText("Facile");
        btn_facile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_facileActionPerformed(evt);
            }
        });
        getContentPane().add(btn_facile, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        btn_normal.setText("Nomal");
        btn_normal.setToolTipText("");
        btn_normal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_normalActionPerformed(evt);
            }
        });
        getContentPane().add(btn_normal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        btn_difficile.setText("Difficile");
        btn_difficile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_difficileActionPerformed(evt);
            }
        });
        getContentPane().add(btn_difficile, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        lbl_niveau.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_niveau.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_niveau.setText("Choisissez votre niveau de jeu ");
        getContentPane().add(lbl_niveau, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 400, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_facileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_facileActionPerformed
        lancerJeu(CadenasJeu.NiveauDifficulte.FACILE);
    }//GEN-LAST:event_btn_facileActionPerformed

    private void btn_normalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_normalActionPerformed
        lancerJeu(CadenasJeu.NiveauDifficulte.NORMAL);
    }//GEN-LAST:event_btn_normalActionPerformed

    private void btn_difficileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_difficileActionPerformed
        lancerJeu(CadenasJeu.NiveauDifficulte.DIFFICILE);
    }//GEN-LAST:event_btn_difficileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetreAccueil().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_difficile;
    private javax.swing.JButton btn_facile;
    private javax.swing.JButton btn_normal;
    private javax.swing.JLabel lbl_niveau;
    // End of variables declaration//GEN-END:variables
}
