/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lucie
 */

import java.util.logging.Level;

public class FenetreFin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreFin.class.getName());

    
    /**
     * Creates new form FenetreFin
     */
    public FenetreFin(boolean gagne, String codeSecret, int tentatives) {
        initComponents();
        if (gagne) {
            lbl_message_fin.setText("BRAVO ! Vous avez trouvé le code en " + tentatives + " tentatives !");
        } else {
            lbl_message_fin.setText("PERDU ! Vous avez épuisé vos tentatives.");
        }
        
        lbl_code_secret.setText("Le code secret était : " + codeSecret);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_message_fin = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_code_secret = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bouton_recommencer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_message_fin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_message_fin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_message_fin.setText("message fin");
        getContentPane().add(lbl_message_fin, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 30, 420, -1));

        jPanel1.setLayout(new java.awt.GridLayout(3, 1));

        lbl_code_secret.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_code_secret.setText("code secret");
        lbl_code_secret.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 255), 2));
        jPanel1.add(lbl_code_secret);

        jLabel1.setText("  ");
        jPanel1.add(jLabel1);

        bouton_recommencer.setText("Recommencer");
        bouton_recommencer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_recommencerActionPerformed(evt);
            }
        });
        jPanel1.add(bouton_recommencer);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bouton_recommencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_recommencerActionPerformed
    try {
        FenetreAccueil accueil = new FenetreAccueil();
        accueil.setVisible(true);
        this.dispose();
    } catch (Exception ex) {
        logger.log(Level.SEVERE, "Impossible d'ouvrir FenetreAccueil", ex);
    }
    }//GEN-LAST:event_bouton_recommencerActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_recommencer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_code_secret;
    private javax.swing.JLabel lbl_message_fin;
    // End of variables declaration//GEN-END:variables
}
